REM RUN FROM VS.NET PROMPT
@PAUSE

REM UNREGISTER COM OBJECTS, THEN REGISTER
REM FOR INSTALL IN GLOBAL ASSEMBLY, SIGN 
regasm /u DokanNFC-ShellExt.dll
regasm /codebase DokanNFC-ShellExt.dll
REM REGISTER AS SHELL OBJECTS IN REGISTRY
install.reg
